//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asset.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public int AssetID { get; set; }
        public Nullable<int> PurchaseOrderID { get; set; }
        public Nullable<int> DeclarationID { get; set; }
        public Nullable<int> AssetCostGLAcctNumber { get; set; }
        public Nullable<int> AccumulatedDepreciationGLAcctNumber { get; set; }
        public Nullable<int> DepreciationExpenseGLAcctNumber { get; set; }
        public string AreaDepartment { get; set; }
        public string AssetType1 { get; set; }
        public string CategoryType { get; set; }
        public Nullable<System.DateTime> DateAcquired { get; set; }
        public Nullable<System.DateTime> PlacedInService { get; set; }
        public Nullable<int> Life { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> DepreciableBasis { get; set; }
        public Nullable<decimal> CurrentDepreciation { get; set; }
        public Nullable<decimal> AccumulatedDepreciation { get; set; }
        public Nullable<System.DateTime> RetirementDate { get; set; }
        public string TagNumber { get; set; }
        public string NewTagNumber { get; set; }
        public string Brand { get; set; }
        public string ModelNumber { get; set; }
        public string SerialNumber { get; set; }
        public string AssetResponsible { get; set; }
        public string InvoiceNumber { get; set; }
    
        public virtual Declaration Declaration { get; set; }
        public virtual Purchasing Purchasing { get; set; }
    }
}
