//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asset.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Declaration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Declaration()
        {
            this.Assets = new HashSet<Asset>();
        }
    
        public int DeclarationID { get; set; }
        public Nullable<int> PurchaseOrderID { get; set; }
        public string UOM { get; set; }
        public Nullable<decimal> AssetQuantityCustom { get; set; }
        public string GoodsDeclarationNumber { get; set; }
        public Nullable<System.DateTime> GoodsDeclarationSelectivityDate { get; set; }
        public string GoodsDeclarationReference { get; set; }
        public string TariffItemNumberHTS { get; set; }
        public string SupplierNameImportExport { get; set; }
        public Nullable<decimal> GoodsDeclarationAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset> Assets { get; set; }
        public virtual Purchasing Purchasing { get; set; }
    }
}
