//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asset.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepreciationExpenseGLAcct
    {
        public int IdDeprecationExpenseGL { get; set; }
        public string DeprecationExpenseGLAcct { get; set; }
        public string Comment { get; set; }
    }
}
